### ISSUE TITLE
add the required nav-links

### ISSUE THREAD

**Issue by aashimgarg** [girlscript/Dhenu-Seva#38]
firstly add some dummy links then the logout one(prefer storing the state in the redux)  
@shrushti2000 u can start on this

**Comment by shrushti2000** [comment]
dummy links? As in for what exactly? Can you please elaborate. @aashimgarg

**Comment by aashimgarg** [comment]
> dummy links? As in for what exactly? Can you please elaborate. @aashimgarg

like in case the doctor wants to see his own profile .. there should be a link where he can see this profile.
