### ISSUE TITLE
create doctor-details page and connect it with the mongoDB

### ISSUE THREAD

**Issue by aashimgarg** [girlscript/Dhenu-Seva#42]

**Comment by yashvarshney003** [comment]
Can you explain a little bit or pls give some reference.

**Comment by mohit355** [comment]
Yes have you gone through the code

**Comment by mohit355** [comment]
Actually we have to create a page where doctors can enter their details like Name , Registration, specification,degree, etc. 

We have mongodb schema for that and we need to create a page on the basis of the schema and then connecting that page from backend mongodb

**Comment by aashimgarg** [comment]
hey @yashvarshney003 look at the pr  #46 and you will know get to know much abt the project. So if u want you can work on the other issues

**Comment by saideepesh000** [comment]
@mohit355, @aashimgarg , hey can I try this issue.

**Comment by yashvarshney003** [comment]
Please assign the issue to @saideepesh000
